# Generated by Django 5.1.6 on 2025-03-04 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intrebare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="facultate",
            options={"verbose_name_plural": "facultati"},
        ),
        migrations.CreateModel(
            name="Raspuns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("scor", models.IntegerField(default=0)),
                (
                    "intrebare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="universities.intrebare",
                    ),
                ),
            ],
        ),
    ]
